---
version: '3.5'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_HOSTNAME=rabbitmq
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
      
  simplemusicstore.api:
    image: "mcr.microsoft.com/dotnet/core/runtime:3.0"
    hostname: "simplemusicstore.api"
    depends_on:
      - rabbitmq
      - simplemusicstore.db
    labels:
      NAME: "simplemusicstore.api"
    volumes:
      - "./api/bin:/app"
    ports:
      - "8881:80"
    command: "dotnet /app/SimpleMusicStore.Api.dll"
    
  simplemusicstore.auth:
    image: "mcr.microsoft.com/dotnet/core/sdk:3.0"
    hostname: "simplemusicstore.auth"
    depends_on:
      - rabbitmq
      - simplemusicstore.db
    labels:
      NAME: "simplemusicstore.auth"
    volumes:
      - "./ms/SimpleMusicStore.Auth/bin:/app"
    ports:
      - "8882:80"
    command: "dotnet /app/SimpleMusicStore.Auth.dll"
    
  simplemusicstore.useractivities:
    image: "mcr.microsoft.com/dotnet/core/runtime:3.0"
    hostname: "simplemusicstore.useractivities"
    depends_on:
      - rabbitmq
      - simplemusicstore.db
    labels:
      NAME: "simplemusicstore.useractivities"
    volumes:
      - "./ms/SimpleMusicStore.UserActivities/bin:/app"
    ports:
      - "8883:80"
    command: "dotnet /app/SimpleMusicStore.UserActivities.dll"
    
  simplemusicstore.db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    hostname: "simplemusicstore.db"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Simplemusicst0re"
      ACCEPT_EULA: "Y"